textileio/go-threads

- test/metadata_suite.go
- tstoreds/ds_test.go
- tstoremem/inmem_test.go
- tstoremem/metadata.go
Fixes #23 
When executing the test, I realized that the inmem metadata book wasn't working correctly when getting non-existent keys. So, kind of already paid off. :)
@sanderpick, these changes are parallel to existing PR, so I'll leave it to your preference when to merge it. Leaving it here if the fixed bug may be bothering some tests.
> threadstore: new metadata testsuite & bugfix inmem metadata book

- exe/daemon/main.go
- exe/shell/main.go
- exe/util/util.go
- threads.go
Adds some more niceties to the shell:
- Changes the command paradigm so that you can see output from all threads
- "Enter" a thread with `:enter` such that you can type messages as before
- You can always type a message to a specific thread by prefixing the name: `:team hey!`
- "Exit" a thread with exit 
- Stack commands like `:team:address` (show team's addresses)
- Use `:help` to see available commands
> Shell: Improve thread visibility

- exe/daemon/main.go
- exe/shell/main.go
- exe/util/util.go
- go.mod
- test/threads_suite.go
- threads.go
- ws/client.go
- ws/hub.go
- ws/index.html
- ws/server.go
Closes #55 
- Fixes `exe/util.Build` so that it uses a disc-backed peerstore.
- Registers a "notifee" for the MDNS module in the shell.
- Push records for registered threads to web socket clients. Web clients register for a list of threads. The example `index.html` file shows how you might do this from a list in the URL query params:
```
// Subscribe to thread in URL query
let threads
let params = new URLSearchParams(window.location.search);
if (params.has('thread')) {
threads = params.getAll('thread')
}
let msg = {
type: 'subscribe',
threads: threads
}
socket.send(JSON.stringify(msg))
```
> WebSocket Server

- test/threads_suite.go
Closes #42 
Doh. Of course, the same peers should be used for all these thread tests OR they should be shutdown afterward. Opting for using the same here. Peers were starting up on the same port, which leads to the "connected to wrong peer" error message.
> tests: use the same peers for all tests

- exe/daemon/main.go
- exe/shell/main.go
- go.mod
- go.sum
- test/keybook_suite.go
- test/threads_suite.go
- util/util.go
- ws/client.go
- ws/hub.go
- ws/server.go
Mainly this enables `getRecord` and other related methods to return a JSON encoded record:
```
// Create a new client and connect
window.client = new threads.Client()
client.connect('ws://localhost:8080').then(() => {
const tid = 'bafkufevg3bqezf3mx7vmloyezupzkdx5ozsfudwky3o3c6kiqvqsldy'
const rid = 'bafyreifok6utuqevl7uon255kvdg6edrcfhtnax6eueyuncpl2f3iqjewi'
// Fetch a record
client.getRecord(rid, tid).then((res) => {
console.log(res)
}).catch((err) => {
console.error(err)
})
})
```
Returns...
```
{
"id": "bafyreifok6utuqevl7uon255kvdg6edrcfhtnax6eueyuncpl2f3iqjewi",
"thread_id": "bafkufevg3bqezf3mx7vmloyezupzkdx5ozsfudwky3o3c6kiqvqsldy",
"record_node": "WLTlVlcAFCOsk4NMRcAKLwqDjGNc3hVw/q7n3Ks0HMzi1HxQ+zBRYCPByM+wS5DDzbhUzzfLsGD8cF7vptezMshZevZOrlGSd3eGFD4QXncSe1AYO1cTMY5bHiCU3bwbA0osDdB …
```
> Fix up client method responses

- eventstore/model_test.go
- eventstore/options.go
- eventstore/store.go
- eventstore/store_test.go
- eventstore/util.go
- exe/e2e_counter/reader.go
- exe/e2e_counter/writer.go
- exe/local_eventstore/books/main.go
- exe/local_eventstore/json-books/main.go
- exe/util/util.go
- threads.go
- util/util.go
The `DefaultThreadService` lives in the `eventstore` package.
Originally, I moved it to `util` but we have a circular dependency (utils, threads, threadstore, utils). Trying on `threads`, gets the same circular dependency (threads, threadstore, threads).
Some general points:
- reduced log levels to errors in tests
- Fixes #86 
- Fixes #87 
- Fixes #90
- Fixes #107
- makes tests pass
Besides implementation details, may worth taking a look again to `TestE2EWithThreads` to see how it impacted end user experience, in short:
1. Create `DefaultThreadService()` with an explicit `repoPath`, and optionals: `ListenPort` for listening IPFS Lite, `ProxyPort` if want to avoid default `5050`, and `Debug` for enabling debug lefel.
2. Create the `Store` using that `Threadservice`.
3. Eventually, client …
> store: multiple issue fixes

- eventstore/store_test.go
- threads.go
@sanderpick , here's a PR to show a bug that I'd like your confirmation.
The current PR has the fix, but let me explain the situation.
If you run `TestE2EWithThreads` test (with boostrap commented as shown) without the patch here showed in `threads.go`, the test fail with:
`store_test.go:65: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing failed to find any peer in table"`
If you re-enable boostrap in the test, the test pass OK.
From a conceptual POV, this didn't made sense. Why I would need to boostrap with cafes (since are the defaults now) to let two peers sync to each other, where one of them joined with a thread link?
Was quite hard to figure out since the error was too …
> threads: force connect when adding thread

- client.go
- service.go
- threads.go
This PR disables most concurrency at the peer level. It attempts to achieve safety regarding data consistency. 
All the editions have the same comments so to come back again to fix the edited points, which most probably will be soon.
In short, many `go` statements were removed. And at the `service.go` layer, it leverages `threadservice` `pullLock` lock to serialize all thread*s* interactions (quite extreme since is global lock per threadservice (which already existed for other thing, but is just temporal).
After merging, I'll create a new repo with the underlying app that uncovered some of these things... so to keep it as a reference to be sure we solved this problem correctly.
> threads: temporary concurrency disabling

- eventstore/model.go
- eventstore/model_test.go
- eventstore/query.go
- eventstore/query_json.go
- eventstore/query_jsonmode_test.go
- eventstore/query_test.go
New API for making queries in JSON Mode.
It receives a serializable struct and will return a slice of string which are the json values of the instances of the query.
Created #131 with some further comments about some impact of this new JSONMode feature. I guess that's something to evaluate more in the future, but we all have it somewhat present in our minds.
Comments below.
> store: jsonmode query support

- cbor/event.go
- cbor/record.go
- client.go
- eventstore/storethread.go
- service.go
- threads.go
Fixes #128 
Apart from that main fix, I'll add some further comments with some considerations that I'd like @sanderpick  opinion.
> threads: fetch all unknown records

- eventstore/store.go
- eventstore/storethread.go
More caring about closing properly the glue between Store and Thread (`SingleThreadAdapter`).
We want proper stopping of the flow of (bidirectional) events between these two worlds.
Also Fixes #88, tbh still now sure about it is the correct decision. Switched to considering those situations an Error but keep things alive (instead of Fatal)
Explanation in comments.
> store: proper closing of adapter

- client.go
- eventstore/util.go
- go.mod
- service.go
- threads.go
- util/util.go
Fixes #121 
The main idea of this PR is enabling concurrency per-thread without problems. 
The way to think the concurrency thing is the following:
- `threads` has a `getThreadSemaphore(thread.ID)` which returns a 1-buffered channel that acts as a mutex. The reason for being a channel and not a mutex is that operations can choose to dismiss the action and move on, e.g:
-  `PullThread`, if trying to acquire the channel lock blocks, then it will choose to move on and ignore the action because it means that other work is being done on a thread. Most probably is another pull (can be other things). Whoever called (most probably a ticker) will retry later.
- Almost all other operations that involve changing data from a thread, will acquire the channel and use it like a mutex (with no dismissal …
> threads: fix concurrency

- api/service.go
- eventstore/listeners.go
- eventstore/model.go
- eventstore/store.go
- eventstore/store_test.go
- examples/e2e_counter/reader.go
- go.mod
- go.sum
- jsonpatcher/jsonpatcher.go
Fixes #134 
This PR adds support for a new way of listening changes in `Store`. The old way that simply returned a `chan struct{}` (and good luck!) is gone.
I migrated all uses of old API to the new one that is more general.
Main idea:
The `Store` has a `Listen(..)` API. 
This API receives whatever the number of optional filters to configure what changes you want to hear in flexible ways.
Examples:
- Listen to all changes: `l, err := store.Listen()` (call without args)
- Listen to all changes of some model: `l, err := store.Listen(ListenOption{Model: "Person"})`
- More complex example: listen to Saves in Model2 *or* Saves in Model1 with EntityID "id-i2" *or* deletes of Model1 with id-i1 *or* all deletes from Model2:
```
opts := []ListenOption{ 
ListenOption{Model: "Model2", Type: …
```
> store: support fine-grained store changes notifications

- daemon/main.go
Useful for testing multiple daemons on one machine.
> Allow specifying api addrs

- api/service.go
- eventstore/model.go
- eventstore/query.go
- eventstore/query_json.go
- eventstore/query_jsonmode_test.go
- eventstore/query_test.go
Also added top level `OrderBy` and `OrderByDesc` query creator methods to non-json queries.
> JSONQuery tests use fluent API

- api/client/client.go
- api/client/client_test.go
- api/server.go
- daemon/main.go
- eventstore/manager_test.go
- eventstore/model_test.go
- eventstore/query_jsonmode_test.go
- eventstore/store_test.go
- eventstore/util.go
- examples/chat/main.go
- examples/e2e_counter/main.go
- examples/e2e_counter/reader.go
- examples/e2e_counter/writer.go
- examples/local_eventstore/books/main.go
- examples/local_eventstore/json-books/main.go
- test/threads_suite.go
- threads.go
- util/util.go
From working on daemon + CLI, it's ugly to mix multi addresses w/ normal TCP addresses. This just enforces that all things are multi.
> chore: always use multiaddr

- cbor/event.go
- examples/chat/main.go
Closes #170 
Two fixes:
1. The global chat subscription reports records from all threads, including ones we are just following. So, we can safely skip records from threads where the read key is missing.
2. Fallback to `EventFromNode` when the type assertion in `EventFromRecord` fails.
> chat: fix event decode

- store/util.go
to help investigate storage issues (https://github.com/textileio/go-threads/issues/203), this splits the logstore out of the litestore
> ds: moves logstore out of ipfs datastore

- logstore/lstoreds/addr_book_gc.go
- logstore/lstoreds/headbook.go
- logstore/lstoremem/addr_book.go
- logstore/lstoremem/headbook.go
- service/client.go
- service/server.go
- service/service.go
- store/listeners.go
- store/storethread.go
- util/util.go
- Fixing IDE warnings as `log.Warningf` is now deprecated.
- `AddFollower` should update local addresses _before_ sending logs to the follower.
- `putRecord` should not attempt to "inflate" the given (first) record, as its contents won't be reachable by the `DAGService` yet (block, header, body, are already inflated). However, inflation is required during traversal.
> Service fixes

- service/service.go
- store/util.go
Closes #212 
This will be used to intercept certain requests from sophisticated clients at the service level.
> Service: allow grpc server options

- .github/workflows/publish-grpc-libs.yml
This API doesn't use gogo stuff anymore.
> ci: remove gogo from js publish step

- .gitignore
- Dockerfile
- go.mod
- go.sum
- jsonpatcher/jsonpatcher.go
- service/client.go
- service/service.go
- store/index.go
- store/store.go
- threadsd/main.go
There's some nits included in here as well that I've added locally, just hadn't needed a PR until now.
> Docker: remove flags, enable env vars

- service/service.go
Currently error returned by Start() method of the gRPC server is not handler when instantiating a thread service.
> Service: Handle error when starting gRPC server

- core/thread/id.go
- core/thread/id_test.go
Often times when trying to instantiate a new thread ID I accidentally pass thread.V1 instead of thread.Raw as a first parameter, since it accepts any uint64 you can pass anything there, and it won't fail.
This PR introduces a dedicated type for thread variants to avoid this kind of human errors.
It also removes a global mapping of thread variants to their string representation and instead implements `fmt.Stringer`. This also protects mapping from being mutated from outside the package.
> thread: Use a dedicated type for thread variants

- .gitignore
- go.mod
- store/manager.go
- store/options.go
- store/store.go
- store/util.go
Fixes #203 
A new option is available `WithLowMem(true)` to use direct FileIO and not the mmap (default).
> create option for low mem scenarios avoiding mmap

- cbor/event.go
- cbor/record.go
- core/logstore/logstore.go
- db/manager.go
- db/manager_test.go
- logstore/logstore.go
- logstore/lstoreds/keybook.go
- logstore/lstoremem/keybook.go
- net/api/client/client_test.go
- net/net.go
- net/net_test.go
- test/keybook_suite.go
- test/logstore_suite.go
Closes #176 
- Adds `ClearKeys` and `ClearLogKeys` to `KeyBook`
- Adds `DeleteThread` and `DeleteLog` to `Logstore`
- Adds `RemoveRecord` and `RemoveEvent` in `cbor`
- Implements `DeleteThread` in `net`
To-do:
> Thread Delete

- db/collection.go
- db/collection_test.go
- db/db.go
Adds tests for adding indexes as well
fixes #285 
fixes #284
> Always persist IndexConfig

- .github/workflows/test.yml
- integrationtests/foldersync/foldersync_test.go
Even though the folder sync tests themselves were running serially, I think they were still running in parallel with all the other tests. Here we try to run them in a completely separate CI step.
> Run foldersync tests separately

- integrationtests/foldersync/foldersync_test.go
- net/api/client/client_test.go
- net/client.go
- net/net.go
- net/net_test.go
Closes #309 
Also pushes records added by `AddRecord`.
> Don't wait while pushing

- api/pb/android/threads/src/main/java/io/textile/threads/Client.java
- core/thread/identity.go
I forgot about the Java client in the last little PR. This also switches the public key encoding in the tokens to use Multibase 32 to be consistent with textile.
> Adds missing delete db method

- core/db/db.go
Everything else is lower case... seems like this can be too. base32 in not case sensitive.
> Lowercase instance ID

- go.mod
- go.sum
fixes #189 
previously, if i hit the 'too many open files' error from the threadsd, it wont recover. with this upgrade, it will error but then continue on the next request.
> chore(deps): upgrade grpc to v1.29.0

- db/db.go
`the collection schema should specify an ID string property` should be `the collection schema should specify an _id string property`
> fix(ux): change error string to indicate the correct missing field name

- api/client/client_test.go
- db/collection.go
Closes #337 
Allows a `nil` `_id` attribute on instances that are being created.
> collections: allow missing id on create

- .github/workflows/publish-grpc-libs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- api/client/client_test.go
- core/thread/id.go
- core/thread/id_test.go
- core/thread/protocol.go
- db/manager.go
- examples/chat/main.go
- examples/e2e_counter/writer.go
- net/api/client/client.go
- net/net.go
- net/pubsub.go
- threads/main.go
Sorry @asutula, I didn't grasp that the problem was related to JSON Schemas. So, adding this PR to reduce work. Feel free to take it over. 
Some notes:
- There doesn't seem to be a way to reflect a private attribute. 
- +1 to your original solution.
- This branch has been `reset --hard` to when before you reverted the change, plus a small nits I added. I wasn't able to easily cherry-pick your `better error message` commit, so I made the change manually. 
So, the downside to this, and why I was resistant, is that not there's nothing stopping me from doing `myID := ID("foo")`, which is not a valid `ID`. Calling `String()` on `myID` would panic if we weren't hardcoding the response from `Version()`, which we should probably not be doing anymore since now it's possible to create a version …
> Copy of Make thread.ID just a string alias

- util/util.go
Closes #345 
Switch from the old and dead peers to the `ipfslite` default peers, plus out us-west-1 threads and IPFS host.
> chore: update bootstrap peers

- net/net.go
This is a teeny tiny PR to skip checking for a read key when AddThread is called to add a remote thread. This is a prelim PR to initiate a discussion, as this might not be the best approach.
Here is some context:
When calling `AddThread` from the `net` API, there is currently a check to see if the ThreadKey has Read access (https://github.com/textileio/go-threads/blob/master/net/net.go#L274). This seems like a reasonable check, however, this means no log is created. In settings where the net _client_ does have the Read key, but isn't sharing it with the net _service_ (which is the case with our JS client), this might not be ideal, because there is no log created to push even encrypted updates to. With `CreateThread` this is never an issue, because that check isn't performed, which makes …
> Check for read key or public key when adding Threads

- .gitignore
- core/logstore/logstore.go
- core/thread/id.go
- db/db.go
- db/db_test.go
- db/options.go
- logstore/logstore.go
- logstore/lstoreds/metadata.go
- logstore/lstoremem/metadata.go
- net/api/pb/threadsnet.proto
- net/net.go
- net/net_test.go
- test/logstore_suite.go
Fixes #373, and a better alternative to #372.
The approach here is to simply take advantage of the existing metadata store on the logstore to set a flag as to whether a given log is "managed?" by the local peer. Directly "managed" logs are those logs created or directly added by the local peer. Otherwise, unmanaged logs are those from other peers in a given thread. Related, "owned" logs are those logs for which the peer has the private key. There can only be _one_ "owned" log, versus potentially many "managed" logs.
This should support multiple use cases:
* The local peer is the client peer. One "owned" log is used to interact with a given thread (single-tenant, single-writer setup)
* The local peer is (also) a relay peer. Maybe multiple "managed" logs on behalf of other clients, and zero …
> Flag locally created logs as direct

- net/net.go
- net/net_test.go
Avoids extraneous dials when the data can assume to be already available locally (self dials). This is useful/required for multi-tenant setups where a single peer may be managing multiple threads/logs on behalf of other (remote) peers. For instance, we don't want clients to 'care' if their remote host is already be replicating a thread they are involved in.
Ideally, there would be some logic in here to catch things like this (or other combinations of local vs remote addrs):
```
import manet "github.com/multiformats/go-multiaddr-net"
...
// Early out if we aren't going to be able to dial this peer
if !manet.IsPublicAddr(addr) {
err = fmt.Errorf("addr must be publicly routable address")
return
}
```
But I don't think we can assume, based on address alone, that we can filter something out. …
> Let peers add threads from self + replicate

- db/collection.go
- db/db.go
- db/db_test.go
If a peer calls `addDBFromAddr` _without_ specifying the `Collections`, it can end up in a state where it then received some remote record(s), and since it is not aware of the Collection, it panics upon trying to use the collection in its reducer function (because the collection doesn't exist). This PR catches the nil reference, and bubbles the error back up to the Reduce method, which will now safely throw the error. This also adds a test to check for this possible state. In performing said test, an additional bug was discovered, in that some write transactions on the database were never returning errors from the dispatcher, so this PR also includes that small fix.
Fixes #379 
Fixes #381
> Catch nil collection on reduce

- db/collection.go
- db/collection_test.go
Also adds tests for this edge case to prevent regressions.
Fixes #369 
Note that this still will cause an error if the schema _doesn't_ have an `_id` field. This makes things safer on the Go side. Calling clients should ensure on the client side that this is the case _before_ calling out to the remote Go peer.
> Don't panic on empty schemas when looking for _id

- api/service.go
- db/manager.go
- db/manager_test.go
This fixes a panic when you try to get a database that is based on a thread which _does_ exist, but _is not_ a database thread.
> manager: catch missing dbs

- core/net/net.go
- core/net/options.go
- net/net.go
Oops, of course `AddRecord` can't be protected like this!
> Unprotect net.AddRecord

- db/listeners.go
Closes #401 
All listener channels are directly closed on service shutdown, but when their contexts are canceled, they are closed again via `Close`, which indirectly checks if `c` has been closed already.
> db: fix listeners double close

- api/service.go
- core/thread/identity.go
- db/bench_test.go
- db/index.go
- db/keytransform.go
- db/query.go
- go.mod
- go.sum
- net/api/service.go
- Adds more options to `ds.Query`:
- `Seek` to an instance `ID` before running a query
- `Skip`  is an alternative way to paginate (not as efficient as `Seek`, but a better fit in cases where the IDs aren't dictating result order)
- `Limit` the number of query results
- Adds a couple `ds.Query` helpers:
- `OrderByID`: Specifies ascending ID order for the query results
- `OrderByIDDesc`: Specifies descending ID order for the query results
- Adds `encoding.BinaryMarshaler` and `encoding.BinaryUnmarshaler` to `thread.Identity`
- Adds `Decrypt` to `thread.Identity`
- Adds `Encrypt` to `thread.PubKey`
> Nits for textile mailboxes

- api/client/client_test.go
- common/common.go
- db/db.go
- db/options.go
- examples/chat/main.go
- net/api/client/client_test.go
- net/client.go
- net/net.go
- net/net_test.go
- net/server.go
- threadsd/main.go
Running nodes for some time we've detected that pubsub mechanism combined with threads may produce a lot of unneccesary traffic.
Assuming that every thread has corresponding topic propagated through the pubsub, long-running high-degree nodes accumulate a lot of topics during its lifetime. When some other node establishes connection, it will respond with a huge hello-packet, containing all the topics seen so far, mostly irrelevant to the caller.
Taking into account that pubsub is in fact a secondary channel of event propagation, we can alleviate the problem by making it optional. Pubsub stays enabled by default, so the change won't affect any existing setup, and there is a new NetOption allowing to disable pubsub subsystem in threads completely.
> Make pubsub optional

- go.mod
- threadsd/main.go
- util/util.go
Trying to make `hubd` have working saving logs also to a file, went into a deep rabbit hole.
`hubd` uses an util function on `go-threads` to setup logging. This `SetupLogging` function used env vars to configure the file path output. At some point when we updated `go-log` from `v1.0.0/v1.0.1` to `v1.0.4`, and then something bad happened.
After `ipfs/go-log@v1.0.1` there is a [commit](https://github.com/ipfs/go-log/commit/e1c5faa6442f373b952970b80cb97ec09fd694d5#diff-17a9f1db2982c66c910a1e06f92e6489L34) that from `v1.0.2` and forward makes the `GOLOG_FILE` style of configuring the output file log break the way we are using it.
In that change, they use `go-log/v2` as the underlying logging library, which is OK. But `go-log/v2` only recognizes `GOLOG_FILE` [at `init()` …
> fix logging and avoid replace for textile repo

- common/common.go
- net/client.go
- net/net.go
- net/net_test.go
- net/server.go
Sometimes it is very helpful to be able to set gRPC-parameters for internal communication between nodes, e.g. message size limits, gRPC interceptors etc.
And it'd be nice to have a distinct timeouts for various operations (dial/pull/push), that could be redefined by application.
> Set gRPC dial-options

- api/client/client.go
- api/client/client_test.go
- api/service.go
- db/collection.go
- db/collection_test.go
- db/db.go
Closes #423 
- Removes some cumbersome client types
- Each collection stores its own JS VM and compiled JS functions for resuse
- Properly returns the `writeValidator` and `readFilter` with other collection info in the gRPC API
> Reuse JavaScript VM and other nits

- api/pb/javascript/package-lock.json
- api/pb/javascript/package.json
- core/thread/identity.go
- jsonpatcher/jsonpatcher.go
- jsonpatcher/jsonpatcher_test.go
- net/api/pb/javascript/package-lock.json
- net/api/pb/javascript/package.json
See https://github.com/textileio/go-threads/pull/416#discussion_r481080485
After trying a few different ways to fix this, I landed on just using `interface{}` for `Timestamp`, which allows us to continue bulk-decoding events with potentially mixed `Timestamp` types.
> jsonpatcher: empty interface timestamp

- integrationtests/foldersync/foldersync_test.go
- net/api/client/client_test.go
- net/net.go
Here is a small improvement essential for the ThreadsDB nodes serving a lot of threads. Currently threads are pulled as follows: once in a period goroutines with `pullThread` procedure for all known threads start simultaneously, and it leads to substantial spikes in CPU/memory/network usage. We can pretty easily get rid of the spikes and equalize resource consumption by allocating pull operations evenly during the specified period.
> Balanced thread pulling

- db/README.md
- db/bench_test.go
- db/collection.go
- db/collection_test.go
- db/db.go
- db/db_test.go
- db/dispatcher.go
This PR contains a few small nits and optimizations that make building on offline-first client for ThreadDB easier. The main changes are that a call to Save can now also lead to a Create action being generated if and only if the call to Save includes an existing Instance ID as a simple safety check. This allows callers to write or overwrite an existing Instance, without having to check first if it already exists. An additional change is that Delete now silently ignores missing Instances. This means a client can call delete on an Instance that might have already been deleted while it was offline or similar, without throwing an error.
Finally, the more important addition is the "special" _mod field. This is simple a "readonly" timestamp that gets added to all Instances. Any changes to this …
> Local first optimizations

- db/collection.go
- db/collection_test.go
- jsonpatcher/jsonpatcher.go
This PR fixes a "regression" introduced with the new Save behavior introduced with #450. It also adds a test that should catch this in the future. The issue is that our transactions don't currently provide isolation guarantees, which is particularly problematic when doing remote updates in batches. To get around this, we provide default behavior for "Saving" a non-existent instance. However, we still had an additional check on the patcher that wasn't allowing this. This now allows saves on non-existent instances, but also simplifies the logic on the collection so we aren't special casing this anymore.
> Better behavior when saving non-existent instance

- common/common.go
- core/logstore/logstore.go
- go.mod
- logstore/logstore.go
- logstore/lstoreds/addr_book.go
- logstore/lstoreds/ds_test.go
- logstore/lstoreds/headbook.go
- logstore/lstoreds/keybook.go
- logstore/lstoreds/logstore.go
- logstore/lstoreds/metadata.go
- logstore/lstorehybrid/hybrid_test.go
- logstore/lstorehybrid/logstore.go
- logstore/lstoremem/addr_book.go
- logstore/lstoremem/headbook.go
- logstore/lstoremem/keybook.go
- logstore/lstoremem/logstore.go
- logstore/lstoremem/metadata.go
- test/addr_book_suite.go
- test/headbook_suite.go
- test/keybook_suite.go
- test/metadata_suite.go
- util/finalizer.go
Currently logstore requests are skewed towards the reads, while some retrievals (notably `GetThread`) are pretty expensive, requiring multiple subrequests of logstore components that goes through the series of mutexes preserving data consistency.
So we implemented a new hybrid model of logstore, which is both persistent and enables fast reads. Basically it's just a write-through in-memory cache backed by a datastore for persistency. We combined two existing implementations (lstoreds + lstoremem), such that all reads goes into in-memory store only, and writes are performed in both.
Resulting hybrid model makes request processing order of magnitude faster with a tradeoff of slower writes and increased memory consumption as we're keeping all the data in memory. Given that such a setting is …
> Hybrid logstore

- common/common.go
- db/bench_test.go
- db/db_test.go
- db/index.go
- db/manager_test.go
- db/testutils_test.go
- integrationtests/foldersync/client.go
- integrationtests/foldersync/foldersync_test.go
- threadsd/main.go
- util/datastore/dscopy/main.go
- util/dscopy/main.go
- util/util.go
Adds a small program for copying a badger/mongo datastore to another badger/mongo datastore.
> Datastore copy util

- db/listeners.go
Signed-off-by: Anton Dort-Golts <dortgolts@gmail.com>
> Fix db listener deadlock

- db/index.go
- db/query.go
- db/query_more_test.go
Applies Limit and Skip _after_ other conditions _and_ read filter have been applied. This leads to potentially slightly less efficient queries (because the child query engine can't handle the limits and skips directly), but provides more consistent and accurate/expected results. A test has been added that captures the issue presented in #458, plus a "regression" test was added to ensure we don't over-compensate.
Fixes #458.
Technically this is a bug fix, but it also changes how results are returned when applying limit and skip, so this might need to come with an appropriate version bump?
> Track real counts for limit and skip

- db/query.go
- db/query_more_test.go
Fixes a simple error when skip and limit are chained, leading to what is essentially an offset. This also adds a test for this case. In addition to fixing an error, this PR makes the query more strict about what it "counts". It no longer counts instances that are set to nil by the read filter.
> Fixes error when chaining skip and limit

- net/server.go
Currently number of records returned in the `GetRecordsReply` is limited by a constant value for every log. However, if some thread contains large number of logs we can still hit on a gRPC's message size limit. Instead we can limit total number of records for all logs in the thread.
> Total records limit in the GetRecords reply

- core/logstore/logstore.go
- db/collection_test.go
- logstore/lstoreds/headbook.go
- logstore/lstorehybrid/logstore.go
- logstore/lstoremem/headbook.go
- net/server.go
- test/addr_book_suite.go
- test/headbook_suite.go
- util/util.go
Hi folks, here is another improvement for GetRecords.
This time we propose a new concept: thread edge. Basically it's just a 64-bit deterministic hash of all heads in a thread. Using the edge values we can easily compare two states of the same thread and decide if they are equal without fetching all thread's information from the logstore. Such optimization at first should improve request processing time on a fast path for the frequent GetRecords requests.
As a follow-up: introducing thread edges enables implementing fast checks for thread changes without getting and sending thread information on both  communicating nodes (protocol extension in progress for now).
> Thread edge proposal

- common/common.go
- core/logstore/logstore.go
- go.mod
- go.sum
- integrationtests/foldersync/foldersync_test.go
- logstore/lstoreds/addr_book.go
- logstore/lstoreds/headbook.go
- logstore/lstorehybrid/logstore.go
- logstore/lstoremem/addr_book.go
- net/client.go
- net/net.go
- net/pb/net.pb.go
- net/pb/net.proto
- net/pb/netpb_test.go
- net/queue/common.go
- net/queue/ff.go
- net/queue/ff_test.go
- net/queue/tp.go
- net/queue/tp_test.go
- net/server.go
- test/addr_book_suite.go
- test/headbook_suite.go
- util/finalizer.go
- util/util.go
Follow-up to #477.
Here is a rework of internal node communication patterns. It should significantly reduce traffic and CPU consumption of the nodes in a steady state and make it scale better. Surely, the PR is huge, but unfortunately it turned out to be impractical to divide it into the smaller ones, as all the features play well just being implemented together.
Here is the outline:
* Internal communication protocol for ThreadsDB nodes extended with a new call `ExchangeEdges`. New method enables efficient checks if thread information is in sync between any two nodes, using heads/address edges (digest), and is a replacement for continuous pulling with `GetRecords`. It also helps to reduce communication overhead with both synced and inactive peers.
* Now all calls to `GetLogs`/`GetRecords` …
> Exchange edges

- broadcast/broadcast_test.go
- logstore/lstoreds/addr_book.go
- logstore/lstoreds/headbook.go
- logstore/lstoreds/logstore.go
- net/client.go
- net/pb/net.pb.go
- net/pb/net.proto
- net/server.go
In Anytype we discovered that current synchronisation mechanism of `exchangeEdges` doesn’t provide for cases when we have threads empty logs (i.e. their heads are empty). For example in these cases we exclude such thread from exchange process and thus prevent other node to discover new logs. 
To remedy that I created the same PR as we have in our fork. The idea is that we still exchange information about such threads and send default values for respective hashes. We also made things backward compatible (because essentially previously we also sent empty values as hashes when we responded to `exchangeEdges` request, because 0s are used by default).
> Exchange edges improvements

- README.md
Without this change I get:
```
panic: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address /ip4/127.0.0.1/tcp/6006: missing port in address"
```
> README: fix NewClient() calls

- core/thread/identity.go
- go.mod
- go.sum
- jwt/jwt.go
- jwt/jwt_test.go
See https://github.com/advisories/GHSA-w73w-5m7g-f7qc
Not sure what shall we do to the deployed version.
> upgrade jwt library for security vulnerability

- api/service.go
- common/common.go
- db/db.go
- db/manager.go
- integrationtests/foldersync/client.go
- net/api/service.go
- net/client.go
- net/net.go
- net/net_test.go
- net/server.go
- threadsd/main.go
- util/util.go
- Moves thread pulling control to config vars and flags.
- Makes logging level `INFO` by default instead of just `ERROR`.
> Control thread pulling

- net/net.go
tiny nit, these ERROR logs pop up in monitoring
> net: dont log echangeEdges error as error (too noisy)

- Dockerfile
This PR updates the go version used for building the project in the docker image.
Some advantages include performance benefits and less likely to contain security issues.
> Use go1.17.5 for docker image
