- exe/shell/main.go
- go.mod
- go.sum
- service.go
- test/keybook_suite.go
- threads.go
- threadstore.go
- tstoreds/headbook.go
- tstoreds/keybook.go
- tstoreds/threadstore.go
- tstoremem/keybook.go
- util/util.go
Closes #52 
Depends on https://github.com/textileio/go-textile-core/pull/26.
> Threadstore: move follow & read keys to thread level

- client.go
- exe/shell/main.go
- test/headbook_suite.go
- test/keybook_suite.go
- threads.go
- tstoreds/ds_test.go
- tstoremem/addr_book.go
- tstoremem/keybook.go
- ws/server.go
> lint fixes

- util/util.go
- ws/client.go
- ws/hub.go
This is needed to push new records to clients in a way that they can consume.
> ws: re-enable subscriptions

- threads.go
> threads: dont fail if log is empty on pull

- eventstore/manager.go
- eventstore/manager_test.go
- eventstore/model.go
- eventstore/store.go
- eventstore/storethread.go
Closes #117 
I've gone back and forth on whether or not this is needed. I think it will become more clear soon.
> store: persist json schemas

- api/client/client_test.go
This uses `TestMain` to set up a server and client shared by all tests, but each test still creates its own Store and builds up it's own data etc needed to execute the test. Not creating and shutting down the server and client repeatedly like before seems to have fixed the problem of the tests timing out. 
fixes #146
> Update client test architecture

- api/pb/package.json
> js-client: bump version

- .circleci/config.yml
- api/client/client_test.go
- threads.go
Closes #153
Also, lint nits, clean up circle config file.
> test: non-colliding ports

- eventstore/common.go
- eventstore/dispatcher.go
- eventstore/dispatcher_test.go
- eventstore/keytransform.go
- eventstore/listeners.go
- eventstore/manager.go
- eventstore/model.go
- eventstore/options.go
- eventstore/query.go
- eventstore/query_json.go
- eventstore/store.go
- eventstore/store_test.go
- eventstore/storethread.go
- go.mod
- go.sum
- jsonpatcher/jsonpatcher.go
Fixes #93 
The main intention of this PR is making #93 real. Apart from necessary changes for that issue, I took advantage and did others all under the mantra of simplifying things and make code more coherent.
The PR was bigger than expected, but I'm satisfied with all the changes. Some things in the code were a bit weird, but now all seem to fit more correctly.
I'll add many comments to help review.
~~This PR is still a draft since depends on merging a [`go-textile-core` PR](https://github.com/textileio/go-textile-core/pull/34). When merged, a further `go.mod` change will be necessary.~~
> store: batch txn mutations in single Record

- api/service.go
- eventstore/manager.go
- eventstore/query.go
- eventstore/query_jsonmode_test.go
- eventstore/query_test.go
- eventstore/store.go
- eventstore/store_test.go
- eventstore/storethread.go
- eventstore/util.go
- examples/chat/main.go
Not heavy stuff in this PR.
- Fixes #89 
- Fixes #81 
- Fixes #111
- Fixes #97
- Added some extra missing tests thanks to linter reporting unused var 
- Fixes some lint checks.
Also fixes tests that were broken in master due to a previous merged PR. All working now.
Extra code comments to help review.
> Multiple issue fixes

- api/client/client.go
- api/client/client_test.go
- api/server.go
- eventstore/options.go
Just a couple small things I encountered when combining this lib with `textile`.
> nits: found during textile integration

- eventstore/manager.go
Small one to fix store reloading when an entity does not yet exist.
> manager: fix reloading stores

- .github/workflows/publish-grpc-libs.yml
Signed-off-by: andrew <andrew@textile.io>
> ci: temporarily allows dart/lib folder into repo for pub publish step

- service/service.go
This allows us to use web sockets for connection from browsers and nodejs.
> Adds support for websocket connections and cors

- README.md
> readme: adds a table of available libraries

- README.md
preview https://gist.github.com/andrewxhill/1259c281e7700d29205b79babe1b42d2
> readme: adds basic table of threads highlights

- api/client/client.go
- api/client/client_test.go
- api/pb/javascript/package-lock.json
- go.mod
- go.sum
- threads/main.go
keeping this in wip for a few, would like to tighten up a couple of areas. it provides the minimal set of things for now, ability to 
* `use` a store by id
* once using a store `getModel` by name
* or once using a store, `listen` to all updates
> shell: add simple developer shell

- .github/workflows/release.yml
Signed-off-by: andrew <andrew@textile.io>
> ci: updates radiusnetworks/release-asset-action to v2

- .github/workflows/release.yml
little tweak to not spill release files everywhere when unzipped
> Contain files when release is uncompressed

- dist/install
fixes install script to successfully install both threads and threadsd or give feedback on specific failures.
> ci: fixes install script 

- .github/workflows/release.yml
Signed-off-by: Aaron Sutula <hi@asutula.com>
> Use a unique dir name

- .github/workflows/release.yml
Signed-off-by: Aaron Sutula <hi@asutula.com>
> Little fix while prepping release

- .github/workflows/release.yml
problem of empty windows builds reported in public slack, this should fix it.
> Recursively bundle windows build

- db/db.go
Fixing fallout from a GH merge...
> db: add back missing const

- cbor/event.go
- cbor/record.go
- core/net/record.go
- core/thread/token.go
- net/api/client/client_test.go
- net/client.go
- net/net.go
- net/net_test.go
- net/server.go
I forgot to push this last change for https://github.com/textileio/go-threads/pull/293.
> Use author pub key as first rec sig payload

- logstore/logstore.go
- net/client.go
- net/net.go
These are the fixes we identified in the course of working on my folder sync branch, but here, applied to master.
> Bug fix picks

- .github/workflows/publish-grpc-libs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
- go.mod
> go: update to 1.14

- db/query.go
The gRPC is doing JSON unmarshaling. If the _Value_ field has some unknown key, then none of the allowed types _String_, _Bool_, or _Float_ will be non-nil. This will cause a problem on query execution.
Adding now some logic validate a query before execution.
Fixes #314
> query: validate query before execution

- common/common.go
> revert to explicit peerstore for persistence

- jsonpatcher/jsonpatcher.go
Partially address #332 
Here is the example I had an issue with. It was solved by this PR. 
https://gist.github.com/requilence/a9d1c4ceab32e1f09b1ce2f3e895e242
It's too dumb to add it as a test, cause it can be false-positive. But maybe I can modify it somehow. Let me know.
> jsonpatcher: sort events by ts in the reducer

- db/collection.go
- db/collection_test.go
- db/db.go
> Ensure URL-safe collection names

- api/pb/dart/pubspec.yaml
https://github.com/textileio/go-threads/runs/654152762?check_suite_focus=true#step:17:30
> fix(dart): dart grpc lib sdk mismatch protoc output

- common/common.go
- threadsd/main.go
Adds an option for passing in a custom connection manager and exposes flag for it to `threadsd`.
> common: allow custom libp2p connection manager

- crypto/asymmetric/asymmetric_old/asymmetric_old_test.go
- crypto/asymmetric/asymmetric_test.go
- go.mod
> crypto/asymmetric: use alternative curve transformation logic

- threadsd/main.go
Signed-off-by: Carson Farmer <carson.farmer@gmail.com>
This is a direct copy of the solution added here: https://github.com/textileio/textile/pull/263
> Enable keepalive pinging thanks to @asutula

- api/client/client.go
> client: adds block option to request

- db/collection.go
The move to a collection-wide JS VM raised this issue... we get data races in textile when pushing/pulling aggressively on a bucket.
> db: goja runtime is not thread safe

- db/db.go
- jsonpatcher/jsonpatcher_test.go
> jsonpatcher: fix gob-encode of old ts events

- .github/workflows/release.yml
> ci: fix asset file path

- .github/workflows/release.yml
> ci: cleanup install folder

- .github/workflows/publish-grpc-libs.yml
> ci: allow insecure commands

- broadcast/broadcast_test.go
- db/collection.go
- db/collection_test.go
- db/dispatcher.go
- db/manager.go
- db/query.go
- docker-compose-dev.yml
- docker-compose.yml
- go.mod
- go.sum
- test/addr_book_suite.go
Chore... update to release vs. hash.
> mod: update ds-mongo

- db/listeners.go
Follow-up to #476. Fixing concurrency issues in DB listeners.
> Fix DB listeners

- core/net/net.go
- db/collection_test.go
- integrationtests/testground/baseline-docker.toml
- integrationtests/testground/current-docker.toml
- integrationtests/testground/current-exec.toml
- integrationtests/testground/head-docker.toml
- integrationtests/testground/main.go
- integrationtests/testground/manifest.toml
Signed-off-by: Merlin Ran <merlinran@gmail.com>
> various fixes to the testground tests

- net/client.go
Signed-off-by: mcrakhman <rakhmanov.m@gmail.com>
> Fix nil log crash in get records

- .github/workflows/release.yml
For next release, the release workflow will publish binaries for darwin m1  too.
> Publish binaries for darwin arm64 (m1).

- db/collection.go
Never got around to this... cleaning up to-do list now :)
> db: ensure vm doesnt run forever

- db/collection.go
- db/collection_test.go
timeout was being set at the time of VM creation, not before it's use.
> move vm timeout to where func is called
